name = "SmoothedParticles"
uuid = "b7455f7a-83c6-4046-bd2b-dfe6091272a6"
version = "0.2.3"

[deps]
Match = "7eb4fadd-790c-5f42-8a69-bfa0b872bfbf"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
ReadVTK = "dc215faf-f008-4882-a9f7-a79a826fadc3"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"

[compat]
Match = "1"
StaticArrays = "1"
WriteVTK = "1"
ReadVTK = "0.1.3"
julia = "1.5"
Interpolations = "0.14.0"

